services:
  nfe-exporter:
    image: ghcr.io/matheusconsoli/nfe-exporter:latest
    container_name: nfe-exporter
    volumes:
      - ./config.json:/app/config.json:ro
      - ./output:/app/output
    restart: "no"
